name: Backend 

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ./Mechty-learn-backend/Mechty-learn-backend

jobs:
  backend:
    uses: ./.github/workflows/build-push-and-redeploy.yml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      path: ./Mechty-learn-backend/Mechty-learn-backend
      tag: backend
    secrets:
      render-deploy-url: ${{ secrets.RENDER_URL }}
