name: Build, push image and redeploy

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      tag:
        required: true
        type: string
      build-args:
        required: false
        type: string
    secrets:
      render-deploy-url:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mechty-learn

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{ inputs.path }}
          push: true
          tags: ${{ env.REGISTRY }}/mechty-learn/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          build-args: ${{ inputs.build-args }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/mechty-learn/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  redeploy-on-render:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Deploy
        run: |
          curl "${{ secrets.RENDER_DEPLOY_URL }}"
