name: Build, push images and redeploy

on:
  push:
    branches: [ main ]
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      tag:
        required: true
        type: string
      build-args:
        required: false
        type: string
    secrets:
      render-deploy-url:
        required: true

env:
  REGISTRY: docker.io
  
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ USERNAME }}
          password: ${{ PASSWORD }}
      - name: Build and push backend image
        env:
          REGISTRY: docker.io
          IMAGE_NAME: mechty_backend
          TAG: latest
        run: |
          docker build -t $REGISTRY/galveron/$IMAGE_NAME:$TAG ./Mechty-learn-backend/Mechty-learn-backend
          docker push veronsun/$IMAGE_NAME:$TAG
      - name: Build and push frontend image
        env:
          REGISTRY: docker.io
          IMAGE_NAME: mechty_frontend
          TAG: latest
          DOTNET_BACKEND_URL: ${{ secrets.DOTNET_BACKEND_URL}}
        run: |
          docker build -t veronsun/mechty_frontend:$TAG ./Mechty-learn-frontend
          docker push veronsun/$IMAGE_NAME:$TAG

  redeploy-on-render:
    runs-on: ubuntu-latest
    needs: [build-and-push-images]
    steps:
      - name: Redeploy backend service
        run: |
          curl "${{ secrets.RENDER_BACKEND_URL }}"
      - name: Redeploy frontend service
        run: |
          curl "${{ secrets.RENDER_FRONTEND_URL }}"
